//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsAppointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int cid { get; set; }
        public Nullable<int> aid { get; set; }
        public string pid { get; set; }
        public string regid { get; set; }
        public string message { get; set; }
    
        public virtual article article { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
