//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsAppointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public string sid { get; set; }
        public string prescription_name { get; set; }
        public bool morning { get; set; }
        public bool afternoon { get; set; }
        public bool night { get; set; }
        public int random { get; set; }
        public int quantity { get; set; }
        public string pid { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
